NOTIFY_OK=This book's author and content have been verified. Signed on %s.
NOTIFY_UNSIGNED=This book cannot be verified. Have the author which appears on the book run /verifybook.
NOTIFY_CHANGED_AUTHOR=This book's author has been changed. The original author is %s.
NOTIFY_CHANGED_CONTENT=This book's content has been changed since it was signed. Signed on %s.
NOTIFY_CHANGED_AUTHOR_CONTENT=This book's author and content have been changed since it was signed. The original author is %s. Signed on %s.
