name: ${name}
version: ${version}
main: ${mainClass}
author: royalkingkb
description: Sign written books cryptographically to prevent forgery
api-version: 1.14

commands:
  bookverify:
    description: Information about this BookVerify instance
  signbook:
    description: Cryptographically sign a book
